### ISSUE TITLE
Predictable source URL returns HTTP 404 for specific package and version

### ISSUE THREAD

**Issue by fschrempf** [pypi/conveyor#32]
**Describe the bug**

Redirecting to the source archive as described in the ["Predictable URLs" section in the docs](https://warehouse.pypa.io/api-reference/integration-guide.html#predictable-urls) does not work for specific versions of the `python-can` package.

```
> curl -I https://files.pythonhosted.org/packages/source/p/python-can/python-can-4.4.2.tar.gz                                                                                                                                                                         
HTTP/2 404 
```

The sources are available, see https://pypi.org/project/python-can/#files.

It works fine with older versions of the same package:

```
> curl -I https://files.pythonhosted.org/packages/source/p/python-can/python-can-4.3.0.tar.gz                                                                                                                                                                         
HTTP/2 302
```

**Expected behavior**

```
> curl -I https://files.pythonhosted.org/packages/source/p/python-can/python-can-4.4.2.tar.gz                                                                                                                                                                         
HTTP/2 302
```

**My Platform**

Tested on several different hosts in different networks.

**Comment by ewdurbin** [comment]
The project began publishing their files as `python_can-4.4.2.tar.gz` (note underscore) in their 4.4.x release series (first release on PyPI 4.4.0rc2), so conveyor is correct in reporting that `python-can-4.4.2.tar.gz` does not exist.
