### ISSUE TITLE
Capitalization issues in combination with conda skeleton

### ISSUE THREAD

**Issue by stefdoerr** [pypi/conveyor#6]
**Describe the bug**
It's impossible to fix the capitalization of a PyPI project even on the test server. Once uploaded it stays like that even if the project is deleted and reuploaded.  Problem is that `conda skeleton` expects small caps URLs and it won't find it if it contains capitalized letters (see https://github.com/conda/conda-build/issues/2389)

Now I practically only have the choice of:
1. Testing on the production server which I didn't upload the capitalized project to (and hoping I don't mess anything up)
2. Choosing a different name for my project (highly improbable)
3. Modify the URL in the `conda skeleton` yaml file every time it's generated (makes for ugly code)

**Expected behavior**
Deleting a project on the test server should delete it for good. It's a test server after all.

**To Reproduce**
1. Create a project with capital letters i.e. Mytest and upload it to the test server.  File resides now in `https://test.pypi.io/packages/source/M/Mytest/Mytest-0.0.1.tar.gz`
2. Run `conda skeleton` on it and it creates a script that tries to pull the `tar.gz` but with small caps in the URL like `https://test.pypi.io/packages/source/m/mytest/mytest-0.0.1.tar.gz`
3. Get an error with `conda build` because the small caps URL doesn't exist
4. Delete the package from the PyPI test server
5. Change project name to lower caps `mytest`
5. Reupload the package to the test server
6. Test server puts the files under the capitalized project URL only fixing the filename i.e. `https://test.pypi.io/packages/source/M/Mytest/mytest-0.0.1.tar.gz`

**Comment by ewdurbin** [comment]
Hello @stefdoerr thanks for your report. This belongs on the conveyor project, which is the shim that redirects these legacy URLs into their canonical location. I'm going to transfer the issue there.

**Comment by ewdurbin** [comment]
The long story short here is that conveyor is not performing any normalization on the project name. Support for this could be added with the [packaging.utils.canonicalize_name](https://packaging.pypa.io/en/latest/utils/#packaging.utils.canonicalize_name) utility.

We would probably want to drop [this check](https://github.com/pypa/conveyor/blob/2e3f0bccbbe3c078c390e6eb5a9580bf3aeb5a91/conveyor/views.py#L40-L41) and apply normalization to the `project_name` somewhere in the request handling.

**Comment by stefdoerr** [comment]
Is there any chance to get the project wiped from the test server so that I can use it again before canonicalization becomes a thing? Or is it manual work?

**Comment by stefdoerr** [comment]
Oh seems like it fixed now. Don't know if anyone changed it or it just needed some time to pick up the lower case changes.
